# Generated by Django 5.0.6 on 2024-06-12 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default=None, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('brand_name', models.CharField(max_length=255, null=True, unique=True, verbose_name='brand name')),
                ('description', models.TextField(default='', null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('role', models.IntegerField(choices=[(0, 'individual'), (1, 'company')], default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
