# Generated by Django 5.0.6 on 2024-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='label',
        ),
        migrations.AddField(
            model_name='account',
            name='brand_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='brand name'),
        ),
    ]
